### ISSUE TITLE
Local file parse failure

### ISSUE THREAD

**Issue by cici** [madpah/requirements-parser#18]
A relative local file fails to parse.  Example:  lib/recaptcha-client-1.0.6.tar.gz

Traceback (most recent call last):
  File "pyreqs.py", line 77, in <module>
    main()
  File "pyreqs.py", line 73, in main
    parse_graph(lines)
  File "pyreqs.py", line 47, in parse_graph
    for req in parsed_reqs:
  File "/Library/Python/2.7/site-packages/requirements/parser.py", line 45, in parse
    yield Requirement.parse(line)
  File "/Library/Python/2.7/site-packages/requirements/requirement.py", line 181, in parse
    return cls.parse_line(line)
  File "/Library/Python/2.7/site-packages/requirements/requirement.py", line 159, in parse_line
    pkg_req = Req.parse(line)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2510, in parse
    reqs = list(parse_requirements(s))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2436, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2404, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'lib/recaptcha-client-1.0.6.tar.gz', 'at', '/recaptcha-client-1.0.6.tar.gz')

**Comment by madpah** [comment]
Closing as this is stale and believed to be superseded by #85 included in `0.8.0`.
