### ISSUE TITLE
-e  in requirements.txt not handled properly

### ISSUE THREAD

**Issue by szabgab** [madpah/requirements-parser#84]
```
>>> import requirements
>>> for req in requirements.parse("-e ."): print(req)
... 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/requirements/parser.py", line 87, in parse
    yield Requirement.parse(line)
  File "/usr/local/lib/python3.9/site-packages/requirements/requirement.py", line 251, in parse
    return cls.parse_editable(
  File "/usr/local/lib/python3.9/site-packages/requirements/requirement.py", line 157, in parse_editable
    assert local_match is not None, 'This should match everything'
AssertionError: This should match everything

```

Also

```
>> for req in requirements.parse("-e abc"): print(req)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/requirements/parser.py", line 87, in parse
    yield Requirement.parse(line)
  File "/usr/local/lib/python3.9/site-packages/requirements/requirement.py", line 251, in parse
    return cls.parse_editable(
  File "/usr/local/lib/python3.9/site-packages/requirements/requirement.py", line 157, in parse_editable
    assert local_match is not None, 'This should match everything'
AssertionError: This should match everything
```

The first example can be found in https://github.com/jerryjliu/llama_index and pip seems to allow https://pip.pypa.io/en/stable/reference/requirements-file-format/

**Comment by simahawk** [comment]
I have the same issue. In fact [this REGEX](https://github.com/madpah/requirements-parser/blob/master/requirements/requirement.py#L41) does not cover the simplest case: `-e path/to/package` .
Of course, in such case we cannot get metadata. However, all we need is the pkg name (last bit of the path).

**Comment by g-carre** [comment]
I would have proposed a different fix for this:

I believe the regular expression from

[requirements-parser/requirements/requirement.py](https://github.com/madpah/requirements-parser/blob/1ce923617147dd984c280d56cb1f02fcd3589a7c/requirements/requirement.py#L41)

Line 41 in [1ce9236](https://github.com/madpah/requirements-parser/commit/1ce923617147dd984c280d56cb1f02fcd3589a7c)

 LOCAL_REGEX = re.compile(r'^((?P<scheme>file)://)?(?P<path>[^#]+)#(?P<fragment>\S+)?') 

should be corrected to
LOCAL_REGEX = re.compile(r'^((?P<scheme>file)://)?(?P<path>[^#]+)(#(?P<fragment>\S+))?')
